### PR TITLE
allow custom react options for react-i18next

### PR DESCRIPTION
**Pull request by adrai**

### CODE REVIEW

**Comment by adrai** [comment]
@jimmyn @stevensacks I'm currently preparing a blog post about this plugin... it would be nice if this would get merged so I can finish my blog post ;-)

**Review by jimmyn — APPROVED** [review]
Approved

**Comment by adrai** [comment]
Awesome 👍

**Comment by jimmyn** [comment]
@adrai when you have your article published please do a PR and add it to README.md

**Comment by adrai** [comment]
https://dev.to/adrai/best-internationalization-for-gatsby-mkf

**Pull request merged**
